# Generated by Django 5.0.4 on 2024-04-14 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0002_alter_post_publish_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 14, 20, 16, 29, 384682, tzinfo=datetime.timezone.utc)),
        ),
    ]
