# Generated by Django 5.0.4 on 2024-04-15 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0008_alter_post_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 15, 7, 52, 0, 677573, tzinfo=datetime.timezone.utc)),
        ),
    ]
