# Generated by Django 5.0.4 on 2024-04-17 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0012_category_rename_body_post_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(default=1, upload_to='img/blog/post_images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='img/blog/category_images/'),
        ),
    ]
