# Generated by Django 5.0.4 on 2024-04-17 21:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createblog', '0013_remove_image_url_image_image_alter_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='publication_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
