# Generated by Django 5.0.4 on 2024-04-15 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listproduit', '0002_remove_produit_categories_produit_categorie'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.ImageField(default=1, upload_to='produit_images'),
            preserve_default=False,
        ),
    ]
